# Generated by Django 5.1.4 on 2025-04-06 13:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title of the campaign.', max_length=255)),
                ('description', models.TextField(help_text='Detailed description of the campaign.')),
                ('goal_amount', models.DecimalField(decimal_places=2, help_text='The target amount to be raised.', max_digits=12)),
                ('total_donated', models.DecimalField(decimal_places=2, default=0, help_text='Total donations received.', max_digits=12)),
                ('unallocated_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount not yet spent from total donations.', max_digits=12)),
                ('start_date', models.DateTimeField(auto_now_add=True, help_text='Campaign creation timestamp.')),
                ('end_date', models.DateTimeField(blank=True, help_text='Optional end date for the campaign.', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Indicates if the campaign is currently active.')),
                ('verified', models.BooleanField(default=False, help_text='Admin verification status.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('organizer', models.ForeignKey(help_text='User who created and manages the campaign.', on_delete=django.db.models.deletion.CASCADE, related_name='campaigns', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Campaign',
                'verbose_name_plural': 'Campaigns',
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount donated.', max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Donation timestamp.')),
                ('transaction_id', models.CharField(help_text='Unique transaction ID for tracking.', max_length=255, unique=True)),
                ('is_fully_allocated', models.BooleanField(default=False, help_text='Flag indicating if the donation is fully used.')),
                ('campaign', models.ForeignKey(help_text='Campaign to which the donation was made.', on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='campaigns.campaign')),
                ('donor', models.ForeignKey(blank=True, help_text='User who made the donation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Donation',
                'verbose_name_plural': 'Donations',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(help_text='Brief description of the expense.', max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Amount spent.', max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Expense creation timestamp.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('campaign', models.ForeignKey(help_text='Campaign for which the expense was made.', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(help_text='User who created the expense record.', on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
            },
        ),
        migrations.CreateModel(
            name='FundAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allocated_amount', models.DecimalField(decimal_places=2, help_text='Amount allocated from donation.', max_digits=12)),
                ('donation', models.ForeignKey(help_text='Donation being allocated to an expense.', on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='campaigns.donation')),
                ('expense', models.ForeignKey(help_text='Expense to which the donation is allocated.', on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='campaigns.expense')),
            ],
            options={
                'verbose_name': 'Fund Allocation',
                'verbose_name_plural': 'Fund Allocations',
            },
        ),
        migrations.CreateModel(
            name='FundWithdrawalRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Requested withdrawal amount.', max_digits=12)),
                ('timestamp', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the request.')),
                ('is_approved', models.BooleanField(default=False, help_text='Approval status of the withdrawal request.')),
                ('reviewed_at', models.DateTimeField(blank=True, help_text='Timestamp when request was reviewed.', null=True)),
                ('campaign', models.ForeignKey(help_text='Campaign from which funds are being withdrawn.', on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to='campaigns.campaign')),
                ('requested_by', models.ForeignKey(help_text='User requesting the withdrawal.', on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, help_text='Admin who reviewed the request.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='withdrawal_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Fund Withdrawal Request',
                'verbose_name_plural': 'Fund Withdrawal Requests',
            },
        ),
        migrations.CreateModel(
            name='Placement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the placement (e.g., 'Website Banner').", max_length=255)),
                ('url', models.URLField(help_text='URL where this placement leads to.')),
                ('qr_code', models.ImageField(blank=True, help_text='QR code image for offline tracking.', null=True, upload_to='qrcodes/')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp when the placement was created.')),
                ('is_deleted', models.BooleanField(default=False, help_text='Soft delete flag.')),
                ('campaign', models.ForeignKey(help_text='Associated campaign for this placement.', on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='campaigns.campaign')),
                ('created_by', models.ForeignKey(help_text='User who created this placement.', on_delete=django.db.models.deletion.CASCADE, related_name='placements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Placement',
                'verbose_name_plural': 'Placements',
            },
        ),
        migrations.AddField(
            model_name='donation',
            name='placement',
            field=models.ForeignKey(blank=True, help_text='Placement through which the donation was made.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='campaigns.placement'),
        ),
    ]
