# Generated by Django 5.1.4 on 2025-04-06 14:22

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='external_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public UUID for external reference.', unique=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='external_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public UUID for external reference.', unique=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='external_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public UUID for external reference.', unique=True),
        ),
        migrations.AddField(
            model_name='fundallocation',
            name='external_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public UUID for external reference.', unique=True),
        ),
        migrations.AddField(
            model_name='fundwithdrawalrequest',
            name='external_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public UUID for external reference.', unique=True),
        ),
        migrations.AddField(
            model_name='placement',
            name='external_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Public UUID for external reference.', unique=True),
        ),
    ]
