# Generated by Django 5.1.4 on 2025-04-07 06:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0002_campaign_external_id_donation_external_id_and_more'),
        ('common', '0002_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='featured_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='campaign_featured_image', to='common.file'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='campaign_images', to='common.file'),
        ),
        migrations.AddField(
            model_name='expense',
            name='receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.file'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='qr_code',
            field=models.ForeignKey(blank=True, help_text='QR code image for offline tracking.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.file'),
        ),
    ]
