# Generated by Django 5.1.4 on 2025-04-08 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0003_campaign_featured_image_campaign_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='placement',
            name='url',
            field=models.URLField(blank=True, help_text='URL where this placement leads to.', null=True),
        ),
    ]
