# Generated by Django 5.1.4 on 2025-04-08 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0005_donation_status'),
        ('common', '0003_alter_file_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='placement',
            name='donation_card',
            field=models.ForeignKey(blank=True, help_text='QR code image for offline tracking.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donation_card', to='common.file'),
        ),
        migrations.AlterField(
            model_name='placement',
            name='qr_code',
            field=models.ForeignKey(blank=True, help_text='QR code image for offline tracking.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qr_code', to='common.file'),
        ),
    ]
